/**
 * Mock Data for Campaign Demo
 * Used when API is not available or for testing
 */

import type {
    CampaignResponse,
    CampaignSlotResponse,
    CampaignSlotProductResponse
} from './types';

// Helper to generate future timestamps
const now = new Date();
const addHours = (hours: number) => new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();
const addDays = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

export const mockProducts: CampaignSlotProductResponse[] = [
    {
        id: 'prod-1',
        slotId: 'slot-1',
        productId: 'p-1',
        productName: 'iPhone 15 Pro Max 256GB',
        productThumbnail: 'https://picsum.photos/seed/iphone/400/400',
        shopId: 'shop-1',
        shopName: 'Apple Store Vietnam',
        originalPrice: 34990000,
        salePrice: 29990000,
        discountPercent: 14,
        stockLimit: 50,
        stockSold: 42,
        stockRemaining: 8,
        isSoldOut: false,
        purchaseLimitPerUser: 1,
        status: 'APPROVED',
    },
    {
        id: 'prod-2',
        slotId: 'slot-1',
        productId: 'p-2',
        productName: 'Samsung Galaxy S24 Ultra 512GB',
        productThumbnail: 'https://picsum.photos/seed/samsung/400/400',
        shopId: 'shop-2',
        shopName: 'Samsung Official',
        originalPrice: 32990000,
        salePrice: 26990000,
        discountPercent: 18,
        stockLimit: 30,
        stockSold: 30,
        stockRemaining: 0,
        isSoldOut: true,
        purchaseLimitPerUser: 1,
        status: 'APPROVED',
    },
    {
        id: 'prod-3',
        slotId: 'slot-1',
        productId: 'p-3',
        productName: 'Sony WH-1000XM5 Wireless Headphones',
        productThumbnail: 'https://picsum.photos/seed/sony/400/400',
        shopId: 'shop-3',
        shopName: 'Sony Vietnam',
        originalPrice: 8990000,
        salePrice: 5990000,
        discountPercent: 33,
        stockLimit: 100,
        stockSold: 67,
        stockRemaining: 33,
        isSoldOut: false,
        purchaseLimitPerUser: 2,
        status: 'APPROVED',
    },
    {
        id: 'prod-4',
        slotId: 'slot-1',
        productId: 'p-4',
        productName: 'MacBook Air M3 15 inch 512GB',
        productThumbnail: 'https://picsum.photos/seed/macbook/400/400',
        shopId: 'shop-1',
        shopName: 'Apple Store Vietnam',
        originalPrice: 42990000,
        salePrice: 36990000,
        discountPercent: 14,
        stockLimit: 20,
        stockSold: 15,
        stockRemaining: 5,
        isSoldOut: false,
        purchaseLimitPerUser: 1,
        status: 'APPROVED',
    },
    {
        id: 'prod-5',
        slotId: 'slot-1',
        productId: 'p-5',
        productName: 'Dyson V15 Detect Vacuum',
        productThumbnail: 'https://picsum.photos/seed/dyson/400/400',
        shopId: 'shop-4',
        shopName: 'Dyson Official',
        originalPrice: 18990000,
        salePrice: 14990000,
        discountPercent: 21,
        stockLimit: 40,
        stockSold: 28,
        stockRemaining: 12,
        isSoldOut: false,
        purchaseLimitPerUser: 1,
        status: 'APPROVED',
    },
    {
        id: 'prod-6',
        slotId: 'slot-1',
        productId: 'p-6',
        productName: 'Nintendo Switch OLED Model',
        productThumbnail: 'https://picsum.photos/seed/nintendo/400/400',
        shopId: 'shop-5',
        shopName: 'Game World',
        originalPrice: 8990000,
        salePrice: 6990000,
        discountPercent: 22,
        stockLimit: 80,
        stockSold: 55,
        stockRemaining: 25,
        isSoldOut: false,
        purchaseLimitPerUser: 2,
        status: 'APPROVED',
    },
];

export const mockSlots: CampaignSlotResponse[] = [
    {
        id: 'slot-1',
        campaignId: 'campaign-1',
        campaignName: 'Flash Sale Cuối Tuần',
        slotDate: addDays(0),
        startTime: addHours(-1),
        endTime: addHours(2),
        status: 'ACTIVE',
        slotName: '12:00 - 15:00',
        maxProducts: 50,
        registeredProducts: 45,
        approvedProducts: 42,
        isFullyBooked: false,
        secondsUntilStart: -3600,
        secondsUntilEnd: 7200,
        durationMinutes: 180,
        products: mockProducts,
    },
    {
        id: 'slot-2',
        campaignId: 'campaign-1',
        campaignName: 'Flash Sale Cuối Tuần',
        slotDate: addDays(0),
        startTime: addHours(3),
        endTime: addHours(6),
        status: 'UPCOMING',
        slotName: '18:00 - 21:00',
        maxProducts: 50,
        registeredProducts: 50,
        approvedProducts: 48,
        isFullyBooked: true,
        secondsUntilStart: 10800,
        secondsUntilEnd: 21600,
        durationMinutes: 180,
    },
    {
        id: 'slot-3',
        campaignId: 'campaign-1',
        campaignName: 'Flash Sale Cuối Tuần',
        slotDate: addDays(1),
        startTime: addHours(24),
        endTime: addHours(27),
        status: 'UPCOMING',
        slotName: '09:00 - 12:00',
        maxProducts: 50,
        registeredProducts: 30,
        approvedProducts: 28,
        isFullyBooked: false,
        secondsUntilStart: 86400,
        secondsUntilEnd: 97200,
        durationMinutes: 180,
    },
];

export const mockCampaigns: CampaignResponse[] = [
    {
        id: 'campaign-1',
        name: 'Flash Sale Cuối Tuần',
        description: 'Giảm giá sốc lên đến 50% cho hàng nghìn sản phẩm công nghệ',
        campaignType: 'FLASH_SALE',
        sponsorType: 'PLATFORM',
        status: 'ACTIVE',
        startDate: addDays(0),
        endDate: addDays(2),
        isRecurring: true,
        recurringStartTime: '12:00',
        recurringEndTime: '21:00',
        bannerUrl: 'https://picsum.photos/seed/flashsale/1200/400',
        thumbnailUrl: 'https://picsum.photos/seed/flashsale-thumb/400/400',
        displayPriority: 1,
        isFeatured: true,
        totalSlots: 6,
        activeSlots: 1,
        totalProducts: 150,
        totalSold: 1250,
        slots: mockSlots,
    },
    {
        id: 'campaign-2',
        name: 'Mega Sale 1.1',
        description: 'Đại hội sale đầu năm - Mua sắm thả ga',
        campaignType: 'MEGA_SALE',
        sponsorType: 'PLATFORM',
        status: 'SCHEDULED',
        startDate: addDays(5),
        endDate: addDays(7),
        bannerUrl: 'https://picsum.photos/seed/megasale/1200/400',
        thumbnailUrl: 'https://picsum.photos/seed/megasale-thumb/400/400',
        displayPriority: 2,
        isFeatured: true,
        totalSlots: 12,
        activeSlots: 0,
        totalProducts: 500,
        totalSold: 0,
    },
    {
        id: 'campaign-3',
        name: 'Daily Deals',
        description: 'Ưu đãi hàng ngày - Săn deal hot mỗi ngày',
        campaignType: 'DAILY_DEAL',
        sponsorType: 'PLATFORM',
        status: 'ACTIVE',
        startDate: addDays(-30),
        endDate: addDays(30),
        isRecurring: true,
        recurringStartTime: '00:00',
        recurringEndTime: '23:59',
        bannerUrl: 'https://picsum.photos/seed/daily/1200/400',
        thumbnailUrl: 'https://picsum.photos/seed/daily-thumb/400/400',
        displayPriority: 3,
        isFeatured: false,
        totalSlots: 30,
        activeSlots: 1,
        totalProducts: 200,
        totalSold: 3500,
    },
];
