export const REJECTED_KEYWORDS = ['repurpose', 'loan', 'violet', 'functionalities', 'consultant', 'visualize', 'international'];
export const CURATED_KEYWORDS = [
    'thời trang', 'điện thoại', 'phụ kiện', 'thiết bị', 'máy tính', 'laptop', 
    'máy ảnh', 'đồng hồ', 'giày', 'thiết bị gia dụng', 'thể thao', 'mẹ',
    'bé', 'nhà', 'làm đẹp', 'sức khỏe', 'sách', 'xe', 'điện tử', 'gia dụng', 'tạp hóa',
];
export const categoryIcons: Record<string, string> = {
    'electronics': '📱', 'electronic': '📱', 'tech': '💻', 'technology': '💻',
    'computer': '💻', 'laptop': '💻', 'phone': '📱', 'mobile': '📱',
    'circuit': '🔌', 'circuits': '🔌',
    'máy tính': '💻', 
    'điện thoại': '📱', 
    'điện tử': '💻', 
    'fashion': '👕', 'clothes': '👕', 'clothing': '👕', 'apparel': '👕',
    'thời trang': '👕', 
    'shoes': '👟', 'footwear': '👟', 'sneakers': '👟',
    'giày': '👟',
    'accessories': '👜', 'bag': '👜', 'bags': '👜',
    'phụ kiện': '👜', 
    'home': '🏠', 'house': '🏠', 'furniture': '🛋️', 'decor': '🖼️',
    'nhà': '🏠', 'nội thất': '🛋️', 'gia dụng': '🍳',
    'kitchen': '🍳', 'bedroom': '🛏️', 'bathroom': '🚿',
    'sports': '⚽', 'sport': '⚽', 'fitness': '💪', 'gym': '💪',
    'thể thao': '⚽',
    'books': '📚', 'book': '📚', 'education': '📖', 'learning': '📖',
    'sách': '📚',
    'beauty': '💄', 'cosmetics': '💄', 'makeup': '💄', 'skincare': '🧴',
    'sắc đẹp': '💄', 'sức khỏe': '💊', 'health': '💊', 'medical': '🏥',
    'personal': '🧴', 'care': '🧴',
    'toys': '🧸', 'toy': '🧸', 'games': '🎮', 'gaming': '🎮',
    'bé': '🧸', 'mẹ & bé': '🧸',
    'automotive': '🚗', 'car': '🚗', 'vehicle': '🚗', 'auto': '🚗',
    'xe': '🚗', 'ô tô': '🚗',
    'food': '🍔', 'beverage': '🥤', 'drink': '🥤', 'restaurant': '🍽️',
    'thực phẩm': '🍔', 'tạp hóa': '🍔',
    'visualize': '👁️', 'consultant': '💼', 'overriding': '⚙️',
    'bedfordshire': '🏛️', 'functionalities': '🔧',
};
