export { OrderStatus, ORDER_STATUS_TEXT } from "@/types/orders/order.dto";
export type {
  OrderResponse,
  OrderItemResponse,
  OrderListResponse,
} from "@/types/orders/order.dto";
import type { OrderResponse } from "@/types/orders/order.types";

// Pricing structure from API response
export interface ShopOrderPricingResponse {
  subtotal: number;
  shopDiscount: number;
  platformDiscount: number;
  shippingDiscount: number;
  originalShippingFee: number;
  appliedVoucherCodes?: string | null;
  totalDiscount: number;
  taxAmount: number;
  shippingFee: number;
  grandTotal: number;
}

// Payment structure from API response
export interface ShopOrderPaymentResponse {
  method: string;
}

// Shipment structure from API response
export interface ShopOrderShipmentResponse {
  trackingNumber?: string | null;
  carrier?: string;
}

export interface ShopOrderItemResponse {
  itemId: string;
  productId: string;
  variantId: string;
  sku: string;
  productName: string;
  imageBasePath?: string | null;
  imageExtension?: string | null;
  variantAttributes?: string | null;
  unitPrice: number;
  quantity: number;
  discountAmount: number;
  lineTotal: number;
}


export interface ShopOrderResponse {
  orderId: string;
  orderNumber: string;
  buyerId: string;
  status: string;
  currency: string;
  pricing: ShopOrderPricingResponse;
  itemCount: number;
  totalQuantity: number;
  customerNote?: string | null;
  internalNote?: string | null;
  cancellationReason?: string | null;
  createdAt: string;
  items: ShopOrderItemResponse[];
  payment: ShopOrderPaymentResponse;
  shipment: ShopOrderShipmentResponse;
  shippingAddress?: any | null;
}

/**
 * Shop Order List Response with pagination
 */
export interface ShopOrderListResponse {
  content: ShopOrderResponse[];
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
  hasNext: boolean;
  hasPrevious: boolean;
  previousPage: number;
  nextPage: number;
  empty: boolean;
  first: boolean;
  last: boolean;
}

/**
 * Full API Response wrapper
 */
export interface ShopOrderApiResponse {
  code: number;
  success: boolean;
  message: string;
  data: ShopOrderListResponse;
}

/**
 * Shop Order Statistics Response - matches backend OrderStatisticsResponse
 */
export interface ShopOrderStatisticsResponse {
  totalOrders: number;
  pendingOrders: number;
  paidOrders: number;
  shippedOrders: number;
  deliveredOrders: number;
  cancelledOrders: number;
  totalRevenue: number;
  averageOrderValue: number;
  ordersByStatus?: Record<string, number>;
  revenueByPeriod?: Record<string, number>;
  newOrdersToday?: number;
  ordersThisWeek?: number;
  ordersThisMonth?: number;
}

// ==================== RE-EXPORT từ Manager ====================
// Keeping for backward compatibility with existing code

// ==================== SHOP-SPECIFIC REQUEST DTOs ====================

/**
 * Shop get orders - Filter request
 * GET /api/v1/shop/orders
 */
export interface ShopGetOrdersRequest {
  status?: string;
  fromDate?: string; // ISO 8601
  toDate?: string; // ISO 8601
  page?: number;
  size?: number;
  sort?: string;
}

/**
 * Shop update order status
 * PUT /api/v1/shop/orders/{orderId}/status
 */
export interface ShopOrderStatusUpdateRequest {
  status: string; // Backend: OrderStatus enum
  note?: string;
  /**
   * Carrier name - Required when status = SHIPPED
   * Values: GHN, SUPERSHIP, CONKIN
   * Optional for other status transitions
   */
  carrier?: string;
  /**
   * Tracking number - Optional
   * Usually auto-generated by carrier API when status = SHIPPED
   * Only used for manual override if needed
   */
  trackingNumber?: string;
}

/**
 * Shop update shipping info (DEPRECATED)
 * PUT /api/v1/shop/orders/{orderId}/shipping
 */
export interface ShopOrderShippingUpdateRequest {
  trackingNumber: string;
  carrier: string;
  estimatedDelivery?: string;
}

// ==================== BATCH MANAGEMENT ====================

/**
 * Shipping Batch for bulk order processing
 */
export interface ShippingBatch {
  batchId: string;
  batchNumber: string;
  createdAt: string;
  updatedAt?: string;
  orderCount: number;
  carrier: string;
  pickupLocation: string;
  pickupDate: string;
  pickupTime: string;
  driverId?: string;
  driverName?: string;
  driverPhone?: string;
  status: BatchStatus;
  orders: OrderResponse[];
  notes?: string;
}

export enum BatchStatus {
  PENDING = "PENDING",
  READY = "READY",
  PICKED_UP = "PICKED_UP",
  IN_TRANSIT = "IN_TRANSIT",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

/**
 * Create shipping batch request
 */
export interface CreateBatchRequest {
  orderIds: string[];
  carrier: string;
  pickupLocation: string;
  pickupDate: string;
  pickupTime: string;
  notes?: string;
}

/**
 * Confirm batch handover request
 */
export interface ConfirmHandoverRequest {
  batchId: string;
  driverId?: string;
  driverName: string;
  driverPhone: string;
  notes?: string;
}

// ==================== RETURN & REFUND MANAGEMENT ====================

/**
 * Return/Refund Request
 */
export interface ReturnRequest {
  requestId: string;
  orderId: string;
  orderNumber: string;
  type: ReturnType;
  reason: string;
  requester: "CUSTOMER" | "SHOP";
  requesterId: string;
  requesterName?: string;
  evidencePhotos: string[];
  status: ReturnStatus;
  deadline: string;
  createdAt: string;
  updatedAt?: string;
  shopResponse?: string;
  shopResponseAt?: string;
  // Embedded order info for quick display
  productName?: string;
  productImage?: string;
  orderTotal?: number;
}

export enum ReturnType {
  RETURN_ONLY = "RETURN_ONLY",
  RETURN_REFUND = "RETURN_REFUND",
  REFUND_ONLY = "REFUND_ONLY",
}

export enum ReturnStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

/**
 * Approve return request
 */
export interface ApproveReturnRequest {
  requestId: string;
  note?: string;
}

/**
 * Reject return request
 */
export interface RejectReturnRequest {
  requestId: string;
  reason: string;
}

// ==================== SHIPPING CARRIER CONFIGURATION ====================

/**
 * Shipping Carrier Configuration
 */
export interface ShippingCarrier {
  carrierId: string;
  name: string;
  displayName: string;
  category: CarrierCategory;
  enabled: boolean;
  codEnabled: boolean;
  maxWeight: number; // in kg
  maxDimensions: Dimensions;
  feeRange?: { min: number; max: number };
  serviceArea: string[]; // List of provinces/cities
  description?: string;
  logo?: string;
  awbTemplate?: string; // URL to AWB template
}

export enum CarrierCategory {
  EXPRESS = "EXPRESS", // 🔥 Hỏa tốc
  FAST = "FAST", // ⚡ Nhanh
  LOCKER = "LOCKER", // 🏪 Tủ nhận hàng
  BULKY = "BULKY", // 📦 Hàng cồng kềnh
  THIRD_PARTY = "THIRD_PARTY", // ➕ Bên thứ 3
}

export interface Dimensions {
  length: number; // cm
  width: number; // cm
  height: number; // cm
}

/**
 * Update carrier configuration request
 */
export interface UpdateCarrierRequest {
  carrierId: string;
  enabled?: boolean;
  codEnabled?: boolean;
  maxWeight?: number;
  maxDimensions?: Dimensions;
  feeRange?: { min: number; max: number };
  serviceArea?: string[];
}

// ==================== PICKUP LOCATIONS ====================

/**
 * Pickup Location for batch shipping
 */
export interface PickupLocation {
  locationId: string;
  name: string;
  address: string;
  phone: string;
  contactPerson: string;
  isDefault: boolean;
  isActive: boolean;
}

// ==================== HELPER TYPES ====================

/**
 * Filter options for batch list
 */
export interface BatchFilterOptions {
  status?: BatchStatus;
  carrier?: string;
  fromDate?: string;
  toDate?: string;
  page?: number;
  size?: number;
}

/**
 * Filter options for return requests
 */
export interface ReturnFilterOptions {
  status?: ReturnStatus;
  type?: ReturnType;
  fromDate?: string;
  toDate?: string;
  page?: number;
  size?: number;
}

// ==================== BULK SHIPPING APIs ====================

/**
 * Bulk order request for confirm/ready-pickup
 * POST /api/v1/shop/orders/bulk-confirm
 * POST /api/v1/shop/orders/bulk-ready-pickup
 */
export interface BulkOrderRequest {
  orderIds: string[];
  pickupMethod?: "PICKUP" | "DROPOFF";
  note?: string;
}

/**
 * Bulk order operation response
 */
export interface BulkOrderResponse {
  successCount: number;
  failedCount: number;
  failures: FailedOrder[];
}

export interface FailedOrder {
  orderId: string;
  orderNumber?: string;
  reason: string;
}

/**
 * Filter counts for pending shipment
 */
export interface FilterCounts {
  overdue: number;
  within24h: number;
  over24h: number;
  carriers: Record<string, number>;
  noCarrier: number;
  total: number;
}

/**
 * Pending shipment response with filter counts
 * GET /api/v1/shop/orders/pending-shipment
 */
export interface PendingShipmentResponse {
  orders: ShopOrderResponse[];
  totalElements: number;
  totalPages: number;
  filterCounts: FilterCounts;
}

/**
 * Pending shipment request params
 */
export interface PendingShipmentRequest {
  status?: string;
  carrier?: string;
  deadline?: "OVERDUE" | "WITHIN_24H" | "OVER_24H";
  page?: number;
  size?: number;
}
