export const PUBLIC_ROUTES = new Set([
  "/",
  "/login",
  "/register",
  "/about",
  "/contact",
  "/privacy",
  "/terms",
  "/products",
  "/category",
  "/data-deletion",
  "/403",
  "/account/verify",
  "/forgot-password",
]);

export const PUBLIC_PREFIXES = [
  "/shop/login",
  "/shop/check",
  "/shop/register",
  "/shop/onboarding",
  "/shop/",
  "/employee/login",
  "/auth/",
  "/products/",
  "/category/",
  "/wishlist/shared/",
  "/test-",
  "/seller/",
  "/_next",
  "/static",
  "/favicon.ico",
];
