
export const COUNTRIES = [
    { value: 'US', label: 'United States (US)' },
    { value: 'VN', label: 'Vietnam (VN)' },
    { value: 'CN', label: 'China (CN)' },
    { value: 'JP', label: 'Japan (JP)' },
    { value: 'KR', label: 'South Korea (KR)' },
    { value: 'GB', label: 'United Kingdom (GB)' },
    { value: 'DE', label: 'Germany (DE)' },
    { value: 'FR', label: 'France (FR)' },
    { value: 'IT', label: 'Italy (IT)' },
    { value: 'ES', label: 'Spain (ES)' },
    { value: 'CA', label: 'Canada (CA)' },
    { value: 'AU', label: 'Australia (AU)' },
    { value: 'NZ', label: 'New Zealand (NZ)' },
    { value: 'SG', label: 'Singapore (SG)' },
    { value: 'MY', label: 'Malaysia (MY)' },
    { value: 'TH', label: 'Thailand (TH)' },
    { value: 'ID', label: 'Indonesia (ID)' },
    { value: 'PH', label: 'Philippines (PH)' },
    { value: 'IN', label: 'India (IN)' },
    { value: 'BR', label: 'Brazil (BR)' },
    { value: 'MX', label: 'Mexico (MX)' },
    { value: 'AR', label: 'Argentina (AR)' },
    { value: 'NL', label: 'Netherlands (NL)' },
    { value: 'BE', label: 'Belgium (BE)' },
    { value: 'CH', label: 'Switzerland (CH)' },
    { value: 'AT', label: 'Austria (AT)' },
    { value: 'SE', label: 'Sweden (SE)' },
    { value: 'NO', label: 'Norway (NO)' },
    { value: 'DK', label: 'Denmark (DK)' },
    { value: 'FI', label: 'Finland (FI)' },
    { value: 'PL', label: 'Poland (PL)' },
    { value: 'RU', label: 'Russia (RU)' },
    { value: 'TR', label: 'Turkey (TR)' },
    { value: 'AE', label: 'United Arab Emirates (AE)' },
    { value: 'SA', label: 'Saudi Arabia (SA)' },
    { value: 'ZA', label: 'South Africa (ZA)' },
];

// Danh sách khu vực phổ biến
export const REGIONS = [
    { value: 'EU', label: 'European Union (EU)' },
    { value: 'APAC', label: 'Asia-Pacific (APAC)' },
    { value: 'NA', label: 'North America (NA)' },
    { value: 'SA', label: 'South America (SA)' },
    { value: 'MEA', label: 'Middle East & Africa (MEA)' },
    { value: 'ASEAN', label: 'ASEAN' },
    { value: 'EURO', label: 'Europe (EURO)' },
    { value: 'LATAM', label: 'Latin America (LATAM)' },
    { value: 'ANZ', label: 'Australia & New Zealand (ANZ)' },
    { value: 'GCC', label: 'Gulf Cooperation Council (GCC)' },
];
